name: ✨ 功能请求
description: 建议新功能或改进
title: '[FEATURE]: '
labels: ['enhancement', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 功能请求

        感谢您提出功能建议！请详细描述您想要的功能。

  - type: textarea
    id: summary
    attributes:
      label: 功能概述
      description: 简要描述这个功能是什么
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能解决了什么问题？为什么需要它？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您建议如何实现这个功能
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过哪些替代方案？
      placeholder: 如果没有替代方案，可以填写 "无"

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能的优先级
      options:
        - 高 (High) - 核心业务需求
        - 中 (Medium) - 重要改进
        - 低 (Low) - 锦上添花
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 预计复杂度
      description: 您认为这个功能的实现复杂度如何
      options:
        - 低 (Low) - 小型功能，几天内完成
        - 中 (Medium) - 中型功能，数周完成
        - 高 (High) - 大型功能，需要数月完成

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 如何判断这个功能已经完成？
      placeholder: |
        - [ ] 用户可以...
        - [ ] 系统会...
        - [ ] 性能满足...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 任何其他相关信息、截图或链接

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在提交前请确认以下项目
      options:
        - label: 这个功能与现有功能不冲突
          required: true
        - label: 我已经搜索了现有的 issue，确保这不是重复请求
          required: true
        - label: 这个功能符合项目的整体架构和设计理念
          required: false
